arm_left_1_joint:
  safety:
    enable_safety: true
arm_left_2_joint:
  safety:
    enable_safety: true
arm_left_3_joint:
  safety:
    enable_safety: true
arm_left_4_joint:
  safety:
    enable_safety: true
arm_left_5_joint:
  safety:
    enable_safety: true
arm_left_6_joint:
  safety:
    enable_safety: true
arm_left_7_joint:
  safety:
    enable_safety: true
arm_right_1_joint:
  safety:
    enable_safety: true
arm_right_2_joint:
  safety:
    enable_safety: true
arm_right_3_joint:
  safety:
    enable_safety: true
arm_right_4_joint:
  safety:
    enable_safety: true
arm_right_5_joint:
  safety:
    enable_safety: true
arm_right_6_joint:
  safety:
    enable_safety: true
arm_right_7_joint:
  safety:
    enable_safety: true
leg_left_1_joint:
  safety:
    enable_safety: true
leg_left_2_joint:
  safety:
    enable_safety: true
leg_left_3_joint:
  safety:
    enable_safety: true
leg_left_4_joint:
  safety:
    enable_safety: true
leg_left_5_joint:
  safety:
    enable_safety: true
leg_left_6_joint:
  safety:
    enable_safety: true
leg_right_1_joint:
  safety:
    enable_safety: true
leg_right_2_joint:
  safety:
    enable_safety: true
leg_right_3_joint:
  safety:
    enable_safety: true
leg_right_4_joint:
  safety:
    enable_safety: true
leg_right_5_joint:
  safety:
    enable_safety: true
leg_right_6_joint:
  safety:
    enable_safety: true
torso_1_joint:
  safety:
    enable_safety: true
torso_2_joint:
  safety:
    enable_safety: true
